---

- name: CMAKE | check if CMAKE is already installed
  shell: command -v cmake >/dev/null 2>&1
  register: cmake_exists
  ignore_errors: yes

- name: CMAKE | Get sources
  become: true
  get_url: url={{cmake_url}} dest={{cmake_tmp}} timeout=180 force=no
  when: not cmake_exists.rc == 0
  register: cmake_downloaded

- name: CMAKE | Extract sources
  become: true
  unarchive: src={{cmake_tmp}}
             dest="/tmp"
             creates={{cmake_build}}
             remote_src=yes
  when: cmake_downloaded.changed
  register: cmake_extract

- name: CMAKE | Bootsrap
  become: true
  shell: chdir={{cmake_build}} ./bootstrap \
    --prefix={{cmake_install_dir}} \
  when: cmake_extract.changed
  register: cmake_configure

- name: CMAKE | Make
  become: true
  shell: chdir={{cmake_build}} make
  when: cmake_configure.changed
  register: cmake_make

- name: CMAKE | Install
  become: true
  shell: chdir={{cmake_build}} make install
  when: cmake_make.changed
  register: cmake_install

- name: CMAKE | add to /usr/local/bin
  become: true
  file: state=link mode=0755 src={{ cmake_install_dir }}/bin/cmake dest="/usr/bin/cmake"
  when: cmake_install.changed

- name: CMAKE | Add CMake to the PATH
  become: true
  action: template src=cmake.sh-template.j2
          dest="/etc/profile.d/cmake.sh"
          mode=0644
  when: cmake_install.changed

- name: CMAKE | cleanup build
  become: true
  file:
    path: "{{ cmake_build }}"
    state: absent
  when: cmake_install.changed

- name: CMAKE | cleanup tmp
  become: true
  file:
    path: "{{ cmake_tmp }}"
    state: absent
  when: cmake_install.changed

...
