---
#4 tasks fil:se for kfieldho.cmake

- name: Check to See if CMake root exists
  stat: path={{cmake_dest_dir}}
  register: opt_kitware

- name: Ensure installation directory
  become: true
  file: state=directory mode=0755 dest={{cmake_dest_dir}}
  when: opt_kitware.stat.exists == False

- name: Check to See if CMake is already installed
  stat: path={{ cmake_install_dir }}/bin/cmake
  register: bin_cmake
  changed_when: bin_cmake.stat.exists == False

- name: Download CMake
  get_url: url={{cmake_url}} dest={{cmake_temp}} validate_certs=False
  register: cmake_downloaded
  when: bin_cmake.stat.exists == False

- name: Install CMake
  become: true
  unarchive: copy=no src={{cmake_temp}} dest={{cmake_dest_dir}}
  when: (bin_cmake.stat.exists == False) and  (cmake_downloaded | success)

- name: add to /usr/local/bin
  become: true
  file: state=link mode=0755 src={{ cmake_install_dir }}/bin/cmake dest="/usr/bin/cmake"
  when: opt_kitware.stat.exists == False

- name: Add CMake to the PATH
  become: true
  action: template src=cmake.sh-template.j2
          dest="/etc/profile.d/cmake.sh"
          mode=0644
  when: cmake_modify_path
